language: go

matrix:
  include:
    - os: linux
      go:
              - "1.13.x"
              - "1.14"

env:
  global:
    - GO111MODULE=on

go_import_path: github.com/gregorynisbet-google/godef

# Add this before_install until we have a definitive resolution on
# https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/2
before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

install: "echo no install step required"

script:
  - go test ./...

    # ensure we can install the "old" way (which will again use vendor)
  - GO111MODULE=off go install

  - go mod vendor
  - go mod tidy

    # https://github.com/golang/go/issues/27868#issuecomment-431413621
  - go list all > /dev/null

  - test -z "$(git status --porcelain)" || (git status; git diff; git show; false)
