# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=rog-go.googlecode.com/hg/exp/abc/audio
GOFILES=\
	audio.go\
	buffer.go\
	format.go\
	util.go\
	w_ringbuf.go\
	w_converter.go\
	w_permute.go\
	w_delay.go\
	w_envelope.go\
	w_graph.go\
	w_mixer.go\
	w_multiply.go\
	w_phaser.go\
	w_time.go\
	w_wave.go\
	w_wavfile.go\


include $(GOROOT)/src/Make.pkg
