include $(GOROOT)/src/Make.$(GOARCH)

TARG=rog-go.googlecode.com/hg/canvas
GOFILES=\
	background.go\
	canvas.go\
	objects.go\
	raster.go\
	text.go\
	value.go\
	fanciful.go\

include $(GOROOT)/src/Make.pkg
