include $(GOROOT)/src/Make.inc

TARG=rog-go.googlecode.com/hg/go9p/g9pc
GOFILES=\
	client.go\
	close.go\
	mount.go\
	open.go\
	pool.go\
	read.go\
	remove.go\
	stat.go\
	walk.go\
	write.go\

include $(GOROOT)/src/Make.pkg
