# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=rog-go.googlecode.com/hg/exp/abc/basic
GOFILES=\
	basic.go\
	echo.go\
	read.go\
	rot13.go\
	stdin.go\
	stdout.go\
	write.go\

include $(GOROOT)/src/Make.pkg
